// <auto-generated />
namespace LoginCol.Huellitas.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RespuestaPregunta2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RespuestaPregunta2));
        
        string IMigrationMetadata.Id
        {
            get { return "201412121807528_RespuestaPregunta2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
